[package]
name = "xipin-resolution"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["pcre2-sys"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcre2-sys = { path = "./pcre2-sys" }
libc = "0.2"
